#!/bin/bash

yabai -m config                              \
  `# global settings`                        \
  mouse_follows_focus          off           \
  focus_follows_mouse          off           \
  window_placement             second_child  \
  window_topmost               off           \
  window_shadow                on            \
  window_opacity               off           \
  window_opacity_duration      0.0           \
  active_window_opacity        1.0           \
  normal_window_opacity        0.90          \
  window_border                off           \
  window_border_width          6             \
  window_origin_display        focused       \
  active_window_border_color   0xff775759    \
  normal_window_border_color   0xff555555    \
  insert_feedback_color        0xffd75f5f    \
  split_ratio                  0.50          \
  auto_balance                 off           \
  mouse_modifier               ctrl          \
  mouse_action1                move          \
  mouse_action2                resize        \
  mouse_drop_action            swap          \
  `# general space settings`                 \
  layout                       bsp           \
  top_padding                  06            \
  bottom_padding               06            \
  left_padding                 06            \
  right_padding                06            \
  window_gap                   06

# float apps by default
FLOAT_APPS=$(cat <<-END
Activity Monitor
Calculator
Calendar
ColorSync Utility
Dictionary
Docker Desktop
Finder
Font Book
Logi Options
Photo Booth
Photos
Preview
PyCharm
QuickTime Player
Rancher Desktop
System Preferences
System Settings
VirtualBox VM
VirtualBox
zoom.us
END)
APP=$(echo "$FLOAT_APPS" | awk -v d='|' '{s=(NR==1?s:s d)$0}END{print s}')
yabai -m rule --add app="$APP" manage=off
echo "yabai configuration loaded.."
