#!/bin/bash

# global settings
yabai -m config                              \
  mouse_follows_focus          off           \
  focus_follows_mouse          off           \
  window_placement             second_child  \
  window_shadow                off           \
  window_opacity               off           \
  normal_window_opacity        0.90          \
  window_origin_display        focused       \
  insert_feedback_color        0xffd75f5f    \
  split_ratio                  0.50          \
  mouse_modifier               ctrl          \
  mouse_action1                move          \
  mouse_drop_action            swap

# general space settings
yabai -m config                              \
  layout                       bsp           \
  top_padding                  06            \
  bottom_padding               06            \
  left_padding                 06            \
  right_padding                06            \
  window_gap                   06

# float apps by default
FLOAT_APPS=$(cat <<-END
Activity Monitor
Calculator
Calendar
ColorSync Utility
Cypress
Dictionary
Docker Desktop
Finder
Font Book
Logi Options
Photo Booth
Photos
Preview
PyCharm
QuickTime Player
Rancher Desktop
System Preferences
System Settings
VIA
VirtualBox VM
VirtualBox
zoom.us
END)
APP=$(echo "$FLOAT_APPS" | awk -v d='|' '{s=(NR==1?s:s d)$0}END{print s}')
yabai -m rule --add app="$APP" manage=off
echo "yabai configuration loaded.."
